; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26131.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Vlad\AppData\Local\Temp\.NETFramework,Version=v4.7.1.AssemblyAttributes.cpp"
